import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { requestService } from '../../services/requestService';
import { applicationService } from '../../services/applicationService';
import { milestoneService } from '../../services/milestoneService';
import { paymentService } from '../../services/paymentService';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import Spinner from '../../components/ui/Spinner';
import { formatCurrency } from '../../utils/formatCurrency';
import { formatDate } from '../../utils/formatDate';
import { FiCheck, FiX, FiInbox, FiLock } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { useTranslation } from 'react-i18next';

export default function ProposalsPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [requests, setRequests] = useState([]);
  const [proposals, setProposals] = useState({});
  const [loading, setLoading] = useState(true);
  const [acceptingId, setAcceptingId] = useState(null);
  const [expandedReq, setExpandedReq] = useState(null);
  const [milestones, setMilestones] = useState({});
  const { t, i18n } = useTranslation(['dashboard', 'common']);

  const isRtl = i18n.language === 'ar';

  useEffect(() => {
    requestService.getByBuyer(user.id)
      .then(async (res) => {
        const reqs = res.data?.requests || [];
        setRequests(reqs);
        const propMap = {};
        await Promise.all(reqs.map(async (r) => {
          try {
            const aRes = await applicationService.getByRequest(r.id);
            propMap[r.id] = aRes.data?.applications || [];
          } catch { propMap[r.id] = []; }
        }));
        setProposals(propMap);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [user.id]);

  const handleAccept = async (requestId, appId, artisanId) => {
    setAcceptingId(appId);
    try {
      // 1. Approve selected application (backend auto-generates milestones + rejects others)
      await applicationService.update(appId, { status: 'Approved' });

      // 2. Get request budget for escrow amount
      const req = requests.find(r => r.id === requestId);
      const budget = Number(req?.budget || 0);

      // 3. Create pending escrow payment
      const paymentRes = await paymentService.create({
        request_id: requestId,
        artisan_id: artisanId,
        totalAmount: budget,
        paymentMethod: 'Cash',
        paymentType: 'escrow',
        status: 'Pending',
      });

      const paymentId = paymentRes?.data?.payment?.id;

      // 4. Reload milestones from server (they were auto-generated by backend)
      await loadMilestones(requestId);

      // 5. Update local state
      setProposals(prev => ({
        ...prev,
        [requestId]: prev[requestId].map(a =>
          a.id === appId ? { ...a, status: 'Approved' } : { ...a, status: 'Rejected' }
        ),
      }));

      toast.success(t('dashboard:proposals.successAccept', 'Proposal accepted! Redirecting to escrow checkout...'));

      // 6. Redirect to checkout with escrow payment
      if (paymentId) {
        setTimeout(() => {
          navigate(`/checkout?payment_id=${paymentId}&request_id=${requestId}`);
        }, 800);
      } else {
        setExpandedReq(requestId);
      }
    } catch (err) {
      console.error('Accept proposal error:', err);
      toast.error(t('dashboard:proposals.failedAccept', 'Failed to accept proposal'));
    } finally {
      setAcceptingId(null);
    }
  };

  const loadMilestones = async (requestId) => {
    try {
      const mRes = await milestoneService.getByRequest(requestId);
      setMilestones(prev => ({ ...prev, [requestId]: mRes.data?.milestones || [] }));
    } catch {}
  };

  if (loading) return <Spinner />;

  return (
    <div style={{ animation: 'fadeInUp 0.4s ease forwards' }}>
      <div style={{ marginBottom: 32 }}>
        <h1 style={{ fontSize: 28, marginBottom: 4 }}>{t('dashboard:proposals.title', 'Proposals')}</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: 15 }}>{t('dashboard:proposals.subtitle', 'Review proposals from artisans')}</p>
      </div>

      {requests.length === 0 ? (
        <div style={{ background: 'var(--surface-primary)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--surface-border)', padding: '80px 32px', textAlign: 'center' }}>
          <FiInbox style={{ fontSize: 56, color: 'var(--surface-border)', marginBottom: 20 }} />
          <h3 style={{ fontSize: 22, fontFamily: 'var(--font-body)', fontWeight: 600, marginBottom: 8 }}>{t('dashboard:proposals.noProposals', 'No proposals yet')}</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: 15 }}>{t('dashboard:proposals.createRequestDesc', 'Create a request to start receiving proposals')}</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          {requests.map(req => {
            const apps = proposals[req.id] || [];
            const reqMilestones = milestones[req.id] || [];
            const hasApproved = apps.some(a => a.status === 'Approved');
            const isExpanded = expandedReq === req.id;

            return (
              <div key={req.id} style={{ background: 'var(--surface-primary)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--surface-border)', overflow: 'hidden' }}>
                <div onClick={() => { setExpandedReq(isExpanded ? null : req.id); if (!isExpanded) loadMilestones(req.id); }}
                  style={{ padding: '20px 24px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: isExpanded ? '1px solid var(--surface-border)' : 'none' }}>
                  <div>
                    <h3 style={{ fontSize: 18, fontFamily: 'var(--font-body)', fontWeight: 600, marginBottom: 4 }}>{req.title}</h3>
                    <p style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
                      {t('common:categories.' + req.category, req.category)} · {t('common:budget', 'Budget')}: {formatCurrency(req.budget)} · {t('dashboard:proposals.proposalCount', { count: apps.length })}
                    </p>
                  </div>
                  <Badge status={hasApproved ? 'Approved' : 'Pending'}>
                    {hasApproved ? t('dashboard:proposals.accepted', 'Accepted') : t('dashboard:proposals.proposalCountBadge', { count: apps.length })}
                  </Badge>
                </div>
                {isExpanded && (
                  <div style={{ padding: '16px 24px' }}>
                    {apps.length === 0 ? (
                      <p style={{ color: 'var(--text-secondary)', fontSize: 14, padding: '16px 0' }}>{t('dashboard:proposals.noProposalsForReq', 'No proposals yet for this request.')}</p>
                    ) : (
                      apps.map(app => (
                        <div key={app.id} style={{ padding: '16px 0', borderBottom: '1px solid var(--surface-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }}>
                          <div style={{ flex: 1 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                              <p style={{ fontWeight: 600, fontSize: 15 }}>{app.artisanName || `${t('dashboard:proposals.artisan', 'Artisan')} #${app.artisan_id}`}</p>
                              <Badge status={app.status} />
                            </div>
                            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{app.proposal}</p>
                            <p style={{ fontSize: 12, color: 'var(--text-tertiary)', marginTop: 4 }}>{formatDate(app.applicationDate)}</p>
                          </div>
                          {app.status === 'Pending' && !hasApproved && (
                            <div style={{ display: 'flex', gap: 8 }}>
                              <Button 
                                size="sm" 
                                onClick={() => handleAccept(req.id, app.id, app.artisan_id)} 
                                icon={FiCheck}
                                loading={acceptingId === app.id}
                              >
                                {t('dashboard:proposals.acceptAndPay', 'Accept & Pay')}
                              </Button>
                            </div>
                          )}
                        </div>
                      ))
                    )}

                    {/* Escrow Info for accepted proposals */}
                    {hasApproved && (
                      <div style={{ marginTop: 16, padding: '14px 18px', background: 'rgba(59, 130, 246, 0.06)', borderRadius: 'var(--radius-md)', border: '1px solid rgba(59, 130, 246, 0.12)', display: 'flex', alignItems: 'center', gap: 12 }}>
                        <FiLock style={{ color: '#3B82F6', fontSize: 18, flexShrink: 0 }} />
                        <div>
                          <p style={{ fontWeight: 600, fontSize: 13, color: '#3B82F6' }}>{t('dashboard:proposals.escrowActive', 'Escrow Payment Active')}</p>
                          <p style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
                            {t('dashboard:proposals.escrowDesc', { amount: formatCurrency(req.budget) })}
                          </p>
                        </div>
                      </div>
                    )}

                    {/* Milestones */}
                    {reqMilestones.length > 0 && (
                      <div style={{ marginTop: 20, paddingTop: 20, borderTop: '1px solid var(--surface-border)' }}>
                        <h4 style={{ fontSize: 16, fontFamily: 'var(--font-body)', fontWeight: 600, marginBottom: 16 }}>{t('dashboard:proposals.milestones', 'Milestones')}</h4>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                          {reqMilestones.map((m, i) => (
                            <div key={m.id || i} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                              <div style={{ width: 32, height: 32, borderRadius: '50%', background: m.status === 'Completed' ? 'var(--success)' : 'var(--surface-tertiary)', color: m.status === 'Completed' ? '#fff' : 'var(--text-secondary)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, fontWeight: 700, flexShrink: 0 }}>
                                {m.status === 'Completed' ? <FiCheck /> : i + 1}
                              </div>
                              <div style={{ flex: 1 }}>
                                <p style={{ fontWeight: 600, fontSize: 14 }}>{m.title}</p>
                                <p style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
                                  {t('dashboard:proposals.dueDate', { date: formatDate(m.dueDate) })}
                                  {m.escrowAmount > 0 && <span style={{ [isRtl ? 'marginRight' : 'marginLeft']: 8, color: 'var(--gold-primary)' }}>· {formatCurrency(m.escrowAmount)}</span>}
                                </p>
                              </div>
                              <Badge status={m.status} />
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
